### GNUmakefile automatically generated by WorkingWiki ###
WW_THIS_PROJECT_SOURCE_FILES = standing-patches-paper.tex Spatial_adaptation/standing-variation-fns.R Spatial_adaptation/standing-variation-plots.R Makefile Spatial_adaptation/local-adaptation.tex Spatial_adaptation/standing-variation.tex standing_patches_refs.bib Spatial_adaptation/preamble.tex Spatial_adaptation/standing-variation-inflorescences.tex Spatial_adaptation/standing-variation-bp-approx.tex GNUmakefile
PREREQUISITE_PROJECTS =
ifndef RESOURCES
  # ProjectEngine provides RESOURCES and the prerequisite project
  # locations.  If they aren't provided, we're in an exported directory.
  export RESOURCES = .resources
  export WW_PUBLISH_URL = /mw/index.php/Special:GetProjectFile?project=Spatial_adaptation&amp;make=false&amp;display=raw&amp;filename=
  export PUBLISH_URL = /mw/index.php/Special:GetProjectFile?project=Spatial_adaptation&amp;make=false&amp;display=raw&amp;filename=
  export WG_SITENAME = Coop
  export WG_SCRIPT_PATH = /mw
endif
include $(RESOURCES)/makefile-before
ifeq ($(filter makefile, $(wildcard makefile)),makefile)
  include makefile
else ifeq ($(filter Makefile, $(wildcard Makefile)),Makefile)
  include Makefile
endif
include $(RESOURCES)/makefile-after
