### GNUmakefile automatically generated by WorkingWiki ###
WW_THIS_PROJECT_SOURCE_FILES = Spatial_adaptation/standing-variation-fns.R Spatial_adaptation/standing-variation-plots.R Makefile Spatial_adaptation/local-adaptation.tex standing_patches_refs.bib Spatial_adaptation/preamble.tex Spatial_adaptation/standing-variation-inflorescences.tex Spatial_adaptation/standing-variation-bp-approx.tex Spatial_adaptation/standing-variation-mixed-model.tex Spatial_adaptation/standing-variation-char-lens.tex Spatial_adaptation/standing-variation-general.tex Spatial_adaptation/standing-variation-pv.tex Spatial_adaptation/hitchhiking-PDE.R sim-lineages.R Spatial_adaptation/lineages.R example-lineages.jpg het-by-recomb.jpg example-lineages-2.jpg Spatial_adaptation/compute-things.R makefile hedrick-table-1.png hedrick-table-2.png hedrick-table-3.png het-by-recomb.png recomb-opportunity-by-distance.png Spatial_adaptation/panmixia.tex Spatial_adaptation/panmixia.R Spatial_adaptation/maize_calcs.R discrete-by-ratio.eps patchy-selection.mk helianthus-ex.tex patchy-selection-fns.R patchy-selection-plots.R maize-ex.tex standing-variation-paper.tex patchy-selection-paper.tex branching-transit.tex generate-patchy-run.R lineages.R sim-patchy-selection.R sim-patchy-selection-fns.R prob-establishment.pdf phase-diagram-log.pdf plotting-fns.R branching-concept.pdf branching-concept.pdf_tex prob-estab-500.pdf prob-estab-62.pdf patchy-sim-writeup-plots.R example-equilibrium.pdf test-sigma.R GNUmakefile
PREREQUISITE_PROJECTS =
ifndef RESOURCES
  # ProjectEngine provides RESOURCES and the prerequisite project
  # locations.  If they aren't provided, we're in an exported directory.
  export RESOURCES = .resources
  export WW_PUBLISH_URL = /mw/index.php/Special:GetProjectFile?project=Spatial_adaptation&amp;make=false&amp;display=raw&amp;filename=
  export PUBLISH_URL = /mw/index.php/Special:GetProjectFile?project=Spatial_adaptation&amp;make=false&amp;display=raw&amp;filename=
  export WG_SITENAME = Coop
  export WG_SCRIPT_PATH = /mw
endif
include $(RESOURCES)/makefile-before
ifeq ($(filter makefile, $(wildcard makefile)),makefile)
  include makefile
else ifeq ($(filter Makefile, $(wildcard Makefile)),Makefile)
  include Makefile
endif
include $(RESOURCES)/makefile-after
